package com.tospery.github.model.core

/**
 * GitHub Trending 的口语筛选项。
 *
 * id 用于拼接 URL 查询参数，name 用于展示。
 */
data class SpokenLanguage(
    val id: String,
    val name: String,
) {
    companion object {
        fun all(): List<SpokenLanguage> = allLanguages

        private val allLanguages: List<SpokenLanguage> = listOf(
            SpokenLanguage(id = "*", name = "Any"),
            SpokenLanguage(id = "ab", name = "Abkhazian"),
            SpokenLanguage(id = "aa", name = "Afar"),
            SpokenLanguage(id = "af", name = "Afrikaans"),
            SpokenLanguage(id = "ak", name = "Akan"),
            SpokenLanguage(id = "sq", name = "Albanian"),
            SpokenLanguage(id = "am", name = "Amharic"),
            SpokenLanguage(id = "ar", name = "Arabic"),
            SpokenLanguage(id = "an", name = "Aragonese"),
            SpokenLanguage(id = "hy", name = "Armenian"),
            SpokenLanguage(id = "as", name = "Assamese"),
            SpokenLanguage(id = "av", name = "Avaric"),
            SpokenLanguage(id = "ae", name = "Avestan"),
            SpokenLanguage(id = "ay", name = "Aymara"),
            SpokenLanguage(id = "az", name = "Azerbaijani"),
            SpokenLanguage(id = "bm", name = "Bambara"),
            SpokenLanguage(id = "ba", name = "Bashkir"),
            SpokenLanguage(id = "eu", name = "Basque"),
            SpokenLanguage(id = "be", name = "Belarusian"),
            SpokenLanguage(id = "bn", name = "Bengali"),
            SpokenLanguage(id = "bh", name = "Bihari languages"),
            SpokenLanguage(id = "bi", name = "Bislama"),
            SpokenLanguage(id = "bs", name = "Bosnian"),
            SpokenLanguage(id = "br", name = "Breton"),
            SpokenLanguage(id = "bg", name = "Bulgarian"),
            SpokenLanguage(id = "my", name = "Burmese"),
            SpokenLanguage(id = "ca", name = "Catalan, Valencian"),
            SpokenLanguage(id = "ch", name = "Chamorro"),
            SpokenLanguage(id = "ce", name = "Chechen"),
            SpokenLanguage(id = "ny", name = "Chichewa, Chewa, Nyanja"),
            SpokenLanguage(id = "zh", name = "Chinese"),
            SpokenLanguage(id = "cv", name = "Chuvash"),
            SpokenLanguage(id = "kw", name = "Cornish"),
            SpokenLanguage(id = "co", name = "Corsican"),
            SpokenLanguage(id = "cr", name = "Cree"),
            SpokenLanguage(id = "hr", name = "Croatian"),
            SpokenLanguage(id = "cs", name = "Czech"),
            SpokenLanguage(id = "da", name = "Danish"),
            SpokenLanguage(id = "dv", name = "Divehi, Dhivehi, Maldivian"),
            SpokenLanguage(id = "nl", name = "Dutch, Flemish"),
            SpokenLanguage(id = "dz", name = "Dzongkha"),
            SpokenLanguage(id = "en", name = "English"),
            SpokenLanguage(id = "eo", name = "Esperanto"),
            SpokenLanguage(id = "et", name = "Estonian"),
            SpokenLanguage(id = "ee", name = "Ewe"),
            SpokenLanguage(id = "fo", name = "Faroese"),
            SpokenLanguage(id = "fj", name = "Fijian"),
            SpokenLanguage(id = "fi", name = "Finnish"),
            SpokenLanguage(id = "fr", name = "French"),
            SpokenLanguage(id = "ff", name = "Fulah"),
            SpokenLanguage(id = "gl", name = "Galician"),
            SpokenLanguage(id = "ka", name = "Georgian"),
            SpokenLanguage(id = "de", name = "German"),
            SpokenLanguage(id = "el", name = "Greek, Modern"),
            SpokenLanguage(id = "gn", name = "Guarani"),
            SpokenLanguage(id = "gu", name = "Gujarati"),
            SpokenLanguage(id = "ht", name = "Haitian, Haitian Creole"),
            SpokenLanguage(id = "ha", name = "Hausa"),
            SpokenLanguage(id = "he", name = "Hebrew"),
            SpokenLanguage(id = "hz", name = "Herero"),
            SpokenLanguage(id = "hi", name = "Hindi"),
            SpokenLanguage(id = "ho", name = "Hiri Motu"),
            SpokenLanguage(id = "hu", name = "Hungarian"),
            SpokenLanguage(id = "ia", name = "Interlingua (International Auxil..."),
            SpokenLanguage(id = "id", name = "Indonesian"),
            SpokenLanguage(id = "ie", name = "Interlingue, Occidental"),
            SpokenLanguage(id = "ga", name = "Irish"),
            SpokenLanguage(id = "ig", name = "Igbo"),
            SpokenLanguage(id = "ik", name = "Inupiaq"),
            SpokenLanguage(id = "io", name = "Ido"),
            SpokenLanguage(id = "is", name = "Icelandic"),
            SpokenLanguage(id = "it", name = "Italian"),
            SpokenLanguage(id = "iu", name = "Inuktitut"),
            SpokenLanguage(id = "ja", name = "Japanese"),
            SpokenLanguage(id = "jv", name = "Javanese"),
            SpokenLanguage(id = "kl", name = "Kalaallisut, Greenlandic"),
            SpokenLanguage(id = "kn", name = "Kannada"),
            SpokenLanguage(id = "kr", name = "Kanuri"),
            SpokenLanguage(id = "ks", name = "Kashmiri"),
            SpokenLanguage(id = "kk", name = "Kazakh"),
            SpokenLanguage(id = "km", name = "Central Khmer"),
            SpokenLanguage(id = "ki", name = "Kikuyu, Gikuyu"),
            SpokenLanguage(id = "rw", name = "Kinyarwanda"),
            SpokenLanguage(id = "ky", name = "Kirghiz, Kyrgyz"),
            SpokenLanguage(id = "kv", name = "Komi"),
            SpokenLanguage(id = "kg", name = "Kongo"),
            SpokenLanguage(id = "ko", name = "Korean"),
            SpokenLanguage(id = "ku", name = "Kurdish"),
            SpokenLanguage(id = "kj", name = "Kuanyama, Kwanyama"),
            SpokenLanguage(id = "la", name = "Latin"),
            SpokenLanguage(id = "lb", name = "Luxembourgish, Letzeburgesch"),
            SpokenLanguage(id = "lg", name = "Ganda"),
            SpokenLanguage(id = "li", name = "Limburgan, Limburger, Limburgish"),
            SpokenLanguage(id = "ln", name = "Lingala"),
            SpokenLanguage(id = "lo", name = "Lao"),
            SpokenLanguage(id = "lt", name = "Lithuanian"),
            SpokenLanguage(id = "lu", name = "Luba-Katanga"),
            SpokenLanguage(id = "lv", name = "Latvian"),
            SpokenLanguage(id = "gv", name = "Manx"),
            SpokenLanguage(id = "mk", name = "Macedonian"),
            SpokenLanguage(id = "mg", name = "Malagasy"),
            SpokenLanguage(id = "ms", name = "Malay"),
            SpokenLanguage(id = "ml", name = "Malayalam"),
            SpokenLanguage(id = "mt", name = "Maltese"),
            SpokenLanguage(id = "mi", name = "Maori"),
            SpokenLanguage(id = "mr", name = "Marathi"),
            SpokenLanguage(id = "mh", name = "Marshallese"),
            SpokenLanguage(id = "mn", name = "Mongolian"),
            SpokenLanguage(id = "na", name = "Nauru"),
            SpokenLanguage(id = "nv", name = "Navajo, Navaho"),
            SpokenLanguage(id = "nd", name = "North Ndebele"),
            SpokenLanguage(id = "ne", name = "Nepali"),
            SpokenLanguage(id = "ng", name = "Ndonga"),
            SpokenLanguage(id = "nb", name = "Norwegian Bokmål"),
            SpokenLanguage(id = "nn", name = "Norwegian Nynorsk"),
            SpokenLanguage(id = "no", name = "Norwegian"),
            SpokenLanguage(id = "ii", name = "Sichuan Yi, Nuosu"),
            SpokenLanguage(id = "nr", name = "South Ndebele"),
            SpokenLanguage(id = "oc", name = "Occitan"),
            SpokenLanguage(id = "oj", name = "Ojibwa"),
            SpokenLanguage(id = "cu", name = "Church Slavic, Old Slavonic, Chu..."),
            SpokenLanguage(id = "om", name = "Oromo"),
            SpokenLanguage(id = "or", name = "Oriya"),
            SpokenLanguage(id = "os", name = "Ossetian, Ossetic"),
            SpokenLanguage(id = "pa", name = "Punjabi, Panjabi"),
            SpokenLanguage(id = "pi", name = "Pali"),
            SpokenLanguage(id = "fa", name = "Persian"),
            SpokenLanguage(id = "pl", name = "Polish"),
            SpokenLanguage(id = "ps", name = "Pashto, Pushto"),
            SpokenLanguage(id = "pt", name = "Portuguese"),
            SpokenLanguage(id = "qu", name = "Quechua"),
            SpokenLanguage(id = "rm", name = "Romansh"),
            SpokenLanguage(id = "rn", name = "Rundi"),
            SpokenLanguage(id = "ro", name = "Romanian, Moldavian, Moldovan"),
            SpokenLanguage(id = "ru", name = "Russian"),
            SpokenLanguage(id = "sa", name = "Sanskrit"),
            SpokenLanguage(id = "sc", name = "Sardinian"),
            SpokenLanguage(id = "sd", name = "Sindhi"),
            SpokenLanguage(id = "se", name = "Northern Sami"),
            SpokenLanguage(id = "sm", name = "Samoan"),
            SpokenLanguage(id = "sg", name = "Sango"),
            SpokenLanguage(id = "sr", name = "Serbian"),
            SpokenLanguage(id = "gd", name = "Gaelic, Scottish Gaelic"),
            SpokenLanguage(id = "sn", name = "Shona"),
            SpokenLanguage(id = "si", name = "Sinhala, Sinhalese"),
            SpokenLanguage(id = "sk", name = "Slovak"),
            SpokenLanguage(id = "sl", name = "Slovenian"),
            SpokenLanguage(id = "so", name = "Somali"),
            SpokenLanguage(id = "st", name = "Southern Sotho"),
            SpokenLanguage(id = "es", name = "Spanish, Castilian"),
            SpokenLanguage(id = "su", name = "Sundanese"),
            SpokenLanguage(id = "sw", name = "Swahili"),
            SpokenLanguage(id = "ss", name = "Swati"),
            SpokenLanguage(id = "sv", name = "Swedish"),
            SpokenLanguage(id = "ta", name = "Tamil"),
            SpokenLanguage(id = "te", name = "Telugu"),
            SpokenLanguage(id = "tg", name = "Tajik"),
            SpokenLanguage(id = "th", name = "Thai"),
            SpokenLanguage(id = "ti", name = "Tigrinya"),
            SpokenLanguage(id = "bo", name = "Tibetan"),
            SpokenLanguage(id = "tk", name = "Turkmen"),
            SpokenLanguage(id = "tl", name = "Tagalog"),
            SpokenLanguage(id = "tn", name = "Tswana"),
            SpokenLanguage(id = "to", name = "Tonga (Tonga Islands)"),
            SpokenLanguage(id = "tr", name = "Turkish"),
            SpokenLanguage(id = "ts", name = "Tsonga"),
            SpokenLanguage(id = "tt", name = "Tatar"),
            SpokenLanguage(id = "tw", name = "Twi"),
            SpokenLanguage(id = "ty", name = "Tahitian"),
            SpokenLanguage(id = "ug", name = "Uighur, Uyghur"),
            SpokenLanguage(id = "uk", name = "Ukrainian"),
            SpokenLanguage(id = "ur", name = "Urdu"),
            SpokenLanguage(id = "uz", name = "Uzbek"),
            SpokenLanguage(id = "ve", name = "Venda"),
            SpokenLanguage(id = "vi", name = "Vietnamese"),
            SpokenLanguage(id = "vo", name = "Volapük"),
            SpokenLanguage(id = "wa", name = "Walloon"),
            SpokenLanguage(id = "cy", name = "Welsh"),
            SpokenLanguage(id = "wo", name = "Wolof"),
            SpokenLanguage(id = "fy", name = "Western Frisian"),
            SpokenLanguage(id = "xh", name = "Xhosa"),
            SpokenLanguage(id = "yi", name = "Yiddish"),
            SpokenLanguage(id = "yo", name = "Yoruba"),
            SpokenLanguage(id = "za", name = "Zhuang, Chuang"),
            SpokenLanguage(id = "zu", name = "Zulu"),
        )
    }
}

/**
 * GitHub Trending 的编程语言筛选项。
 *
 * id 用于拼接 URL 路径，name 用于展示，color 用于 UI 展示语言色点。
 */
data class ProgrammingLanguage(
    val id: String,
    val name: String,
    val color: String? = null,
) {
    companion object {
        fun all(): List<ProgrammingLanguage> = allLanguages

        private val allLanguages: List<ProgrammingLanguage> = listOf(
            ProgrammingLanguage(id = "*", name = "Any", color = "#FB041B"),
            ProgrammingLanguage(id = "1c-enterprise", name = "1C Enterprise", color = "#814CCC"),
            ProgrammingLanguage(id = "abap", name = "ABAP", color = "#E8274B"),
            ProgrammingLanguage(id = "abnf", name = "ABNF"),
            ProgrammingLanguage(id = "actionscript", name = "ActionScript", color = "#882B0F"),
            ProgrammingLanguage(id = "ada", name = "Ada", color = "#02f88c"),
            ProgrammingLanguage(id = "adobe-font-metrics", name = "Adobe Font Metrics"),
            ProgrammingLanguage(id = "agda", name = "Agda", color = "#315665"),
            ProgrammingLanguage(id = "ags-script", name = "AGS Script", color = "#B9D9FF"),
            ProgrammingLanguage(id = "alloy", name = "Alloy", color = "#64C800"),
            ProgrammingLanguage(id = "alpine-abuild", name = "Alpine Abuild"),
            ProgrammingLanguage(id = "ampl", name = "AMPL", color = "#E6EFBB"),
            ProgrammingLanguage(id = "angelscript", name = "AngelScript", color = "#C7D7DC"),
            ProgrammingLanguage(id = "ant-build-system", name = "Ant Build System"),
            ProgrammingLanguage(id = "antlr", name = "ANTLR", color = "#9DC3FF"),
            ProgrammingLanguage(id = "apacheconf", name = "ApacheConf"),
            ProgrammingLanguage(id = "apex", name = "Apex", color = "#1797c0"),
            ProgrammingLanguage(id = "api-blueprint", name = "API Blueprint", color = "#2ACCA8"),
            ProgrammingLanguage(id = "apl", name = "APL", color = "#5A8164"),
            ProgrammingLanguage(id = "apollo-guidance-computer", name = "Apollo Guidance Computer", color = "#0B3D91"),
            ProgrammingLanguage(id = "applescript", name = "AppleScript", color = "#101F1F"),
            ProgrammingLanguage(id = "arc", name = "Arc", color = "#aa2afe"),
            ProgrammingLanguage(id = "asciidoc", name = "AsciiDoc"),
            ProgrammingLanguage(id = "asn.1", name = "ASN.1"),
            ProgrammingLanguage(id = "asp", name = "ASP"),
            ProgrammingLanguage(id = "aspectj", name = "AspectJ", color = "#a957b0"),
            ProgrammingLanguage(id = "assembly", name = "Assembly", color = "#6E4C13"),
            ProgrammingLanguage(id = "ats", name = "ATS", color = "#1ac620"),
            ProgrammingLanguage(id = "augeas", name = "Augeas"),
            ProgrammingLanguage(id = "autohotkey", name = "AutoHotkey", color = "#6594b9"),
            ProgrammingLanguage(id = "autoit", name = "AutoIt", color = "#1C3552"),
            ProgrammingLanguage(id = "awk", name = "Awk"),
            ProgrammingLanguage(id = "ballerina", name = "Ballerina", color = "#FF5000"),
            ProgrammingLanguage(id = "batchfile", name = "Batchfile", color = "#C1F12E"),
            ProgrammingLanguage(id = "befunge", name = "Befunge"),
            ProgrammingLanguage(id = "bison", name = "Bison", color = "#6A463F"),
            ProgrammingLanguage(id = "bitbake", name = "BitBake"),
            ProgrammingLanguage(id = "blade", name = "Blade", color = "#f7523f"),
            ProgrammingLanguage(id = "blitzbasic", name = "BlitzBasic"),
            ProgrammingLanguage(id = "blitzmax", name = "BlitzMax", color = "#cd6400"),
            ProgrammingLanguage(id = "bluespec", name = "Bluespec"),
            ProgrammingLanguage(id = "boo", name = "Boo", color = "#d4bec1"),
            ProgrammingLanguage(id = "brainfuck", name = "Brainfuck", color = "#2F2530"),
            ProgrammingLanguage(id = "brightscript", name = "Brightscript"),
            ProgrammingLanguage(id = "bro", name = "Bro"),
            ProgrammingLanguage(id = "c", name = "C", color = "#555555"),
            ProgrammingLanguage(id = "c%23", name = "C#", color = "#178600"),
            ProgrammingLanguage(id = "c%2B%2B", name = "C++", color = "#f34b7d"),
            ProgrammingLanguage(id = "c-objdump", name = "C-ObjDump"),
            ProgrammingLanguage(id = "c2hs-haskell", name = "C2hs Haskell"),
            ProgrammingLanguage(id = "cap'n-proto", name = "Cap'n Proto"),
            ProgrammingLanguage(id = "cartocss", name = "CartoCSS"),
            ProgrammingLanguage(id = "ceylon", name = "Ceylon", color = "#dfa535"),
            ProgrammingLanguage(id = "chapel", name = "Chapel", color = "#8dc63f"),
            ProgrammingLanguage(id = "charity", name = "Charity"),
            ProgrammingLanguage(id = "chuck", name = "ChucK"),
            ProgrammingLanguage(id = "cirru", name = "Cirru", color = "#ccccff"),
            ProgrammingLanguage(id = "clarion", name = "Clarion", color = "#db901e"),
            ProgrammingLanguage(id = "clean", name = "Clean", color = "#3F85AF"),
            ProgrammingLanguage(id = "click", name = "Click", color = "#E4E6F3"),
            ProgrammingLanguage(id = "clips", name = "CLIPS"),
            ProgrammingLanguage(id = "clojure", name = "Clojure", color = "#db5855"),
            ProgrammingLanguage(id = "closure-templates", name = "Closure Templates", color = "#0d948f"),
            ProgrammingLanguage(id = "cmake", name = "CMake"),
            ProgrammingLanguage(id = "cobol", name = "COBOL"),
            ProgrammingLanguage(id = "coffeescript", name = "CoffeeScript", color = "#244776"),
            ProgrammingLanguage(id = "coldfusion", name = "ColdFusion", color = "#ed2cd6"),
            ProgrammingLanguage(id = "coldfusion-cfc", name = "ColdFusion CFC", color = "#ed2cd6"),
            ProgrammingLanguage(id = "collada", name = "COLLADA"),
            ProgrammingLanguage(id = "common-lisp", name = "Common Lisp", color = "#3fb68b"),
            ProgrammingLanguage(id = "common-workflow-language", name = "Common Workflow Language", color = "#B5314C"),
            ProgrammingLanguage(id = "component-pascal", name = "Component Pascal", color = "#B0CE4E"),
            ProgrammingLanguage(id = "cool", name = "Cool"),
            ProgrammingLanguage(id = "coq", name = "Coq"),
            ProgrammingLanguage(id = "cpp-objdump", name = "Cpp-ObjDump"),
            ProgrammingLanguage(id = "creole", name = "Creole"),
            ProgrammingLanguage(id = "crystal", name = "Crystal", color = "#000100"),
            ProgrammingLanguage(id = "cson", name = "CSON", color = "#244776"),
            ProgrammingLanguage(id = "csound", name = "Csound"),
            ProgrammingLanguage(id = "csound-document", name = "Csound Document"),
            ProgrammingLanguage(id = "csound-score", name = "Csound Score"),
            ProgrammingLanguage(id = "css", name = "CSS", color = "#563d7c"),
            ProgrammingLanguage(id = "csv", name = "CSV"),
            ProgrammingLanguage(id = "cuda", name = "Cuda", color = "#3A4E3A"),
            ProgrammingLanguage(id = "cweb", name = "CWeb"),
            ProgrammingLanguage(id = "cycript", name = "Cycript"),
            ProgrammingLanguage(id = "cython", name = "Cython"),
            ProgrammingLanguage(id = "d", name = "D", color = "#ba595e"),
            ProgrammingLanguage(id = "d-objdump", name = "D-ObjDump"),
            ProgrammingLanguage(id = "darcs-patch", name = "Darcs Patch"),
            ProgrammingLanguage(id = "dart", name = "Dart", color = "#00B4AB"),
            ProgrammingLanguage(id = "dataweave", name = "DataWeave", color = "#003a52"),
            ProgrammingLanguage(id = "desktop", name = "desktop"),
            ProgrammingLanguage(id = "diff", name = "Diff"),
            ProgrammingLanguage(id = "digital-command-language", name = "DIGITAL Command Language"),
            ProgrammingLanguage(id = "dm", name = "DM", color = "#447265"),
            ProgrammingLanguage(id = "dns-zone", name = "DNS Zone"),
            ProgrammingLanguage(id = "dockerfile", name = "Dockerfile", color = "#384d54"),
            ProgrammingLanguage(id = "dogescript", name = "Dogescript", color = "#cca760"),
            ProgrammingLanguage(id = "dtrace", name = "DTrace"),
            ProgrammingLanguage(id = "dylan", name = "Dylan", color = "#6c616e"),
            ProgrammingLanguage(id = "e", name = "E", color = "#ccce35"),
            ProgrammingLanguage(id = "eagle", name = "Eagle"),
            ProgrammingLanguage(id = "easybuild", name = "Easybuild"),
            ProgrammingLanguage(id = "ebnf", name = "EBNF"),
            ProgrammingLanguage(id = "ec", name = "eC", color = "#913960"),
            ProgrammingLanguage(id = "ecere-projects", name = "Ecere Projects"),
            ProgrammingLanguage(id = "ecl", name = "ECL", color = "#8a1267"),
            ProgrammingLanguage(id = "eclipse", name = "ECLiPSe"),
            ProgrammingLanguage(id = "edje-data-collection", name = "Edje Data Collection"),
            ProgrammingLanguage(id = "edn", name = "edn"),
            ProgrammingLanguage(id = "eiffel", name = "Eiffel", color = "#4d6977"),
            ProgrammingLanguage(id = "ejs", name = "EJS", color = "#a91e50"),
            ProgrammingLanguage(id = "elixir", name = "Elixir", color = "#6e4a7e"),
            ProgrammingLanguage(id = "elm", name = "Elm", color = "#60B5CC"),
            ProgrammingLanguage(id = "emacs-lisp", name = "Emacs Lisp", color = "#c065db"),
            ProgrammingLanguage(id = "emberscript", name = "EmberScript", color = "#FFF4F3"),
            ProgrammingLanguage(id = "eq", name = "EQ", color = "#a78649"),
            ProgrammingLanguage(id = "erlang", name = "Erlang", color = "#B83998"),
            ProgrammingLanguage(id = "f%23", name = "F#", color = "#b845fc"),
            ProgrammingLanguage(id = "factor", name = "Factor", color = "#636746"),
            ProgrammingLanguage(id = "fancy", name = "Fancy", color = "#7b9db4"),
            ProgrammingLanguage(id = "fantom", name = "Fantom", color = "#14253c"),
            ProgrammingLanguage(id = "filebench-wml", name = "Filebench WML"),
            ProgrammingLanguage(id = "filterscript", name = "Filterscript"),
            ProgrammingLanguage(id = "fish", name = "fish"),
            ProgrammingLanguage(id = "flux", name = "FLUX", color = "#88ccff"),
            ProgrammingLanguage(id = "formatted", name = "Formatted"),
            ProgrammingLanguage(id = "forth", name = "Forth", color = "#341708"),
            ProgrammingLanguage(id = "fortran", name = "Fortran", color = "#4d41b1"),
            ProgrammingLanguage(id = "freemarker", name = "FreeMarker", color = "#0050b2"),
            ProgrammingLanguage(id = "frege", name = "Frege", color = "#00cafe"),
            ProgrammingLanguage(id = "g-code", name = "G-code", color = "#D08CF2"),
            ProgrammingLanguage(id = "game-maker-language", name = "Game Maker Language", color = "#71b417"),
            ProgrammingLanguage(id = "gams", name = "GAMS"),
            ProgrammingLanguage(id = "gap", name = "GAP"),
            ProgrammingLanguage(id = "gcc-machine-description", name = "GCC Machine Description"),
            ProgrammingLanguage(id = "gdb", name = "GDB"),
            ProgrammingLanguage(id = "gdscript", name = "GDScript", color = "#355570"),
            ProgrammingLanguage(id = "genie", name = "Genie", color = "#fb855d"),
            ProgrammingLanguage(id = "genshi", name = "Genshi"),
            ProgrammingLanguage(id = "gentoo-ebuild", name = "Gentoo Ebuild"),
            ProgrammingLanguage(id = "gentoo-eclass", name = "Gentoo Eclass"),
            ProgrammingLanguage(id = "gerber-image", name = "Gerber Image"),
            ProgrammingLanguage(id = "gettext-catalog", name = "Gettext Catalog"),
            ProgrammingLanguage(id = "gherkin", name = "Gherkin", color = "#5B2063"),
            ProgrammingLanguage(id = "glsl", name = "GLSL"),
            ProgrammingLanguage(id = "glyph", name = "Glyph", color = "#c1ac7f"),
            ProgrammingLanguage(id = "gn", name = "GN"),
            ProgrammingLanguage(id = "gnuplot", name = "Gnuplot", color = "#f0a9f0"),
            ProgrammingLanguage(id = "go", name = "Go", color = "#00ADD8"),
            ProgrammingLanguage(id = "golo", name = "Golo", color = "#88562A"),
            ProgrammingLanguage(id = "gosu", name = "Gosu", color = "#82937f"),
            ProgrammingLanguage(id = "grace", name = "Grace"),
            ProgrammingLanguage(id = "gradle", name = "Gradle"),
            ProgrammingLanguage(id = "grammatical-framework", name = "Grammatical Framework", color = "#ff0000"),
            ProgrammingLanguage(id = "graph-modeling-language", name = "Graph Modeling Language"),
            ProgrammingLanguage(id = "graphql", name = "GraphQL", color = "#e10098"),
            ProgrammingLanguage(id = "graphviz-(dot)", name = "Graphviz (DOT)"),
            ProgrammingLanguage(id = "groovy", name = "Groovy", color = "#e69f56"),
            ProgrammingLanguage(id = "groovy-server-pages", name = "Groovy Server Pages"),
            ProgrammingLanguage(id = "hack", name = "Hack", color = "#878787"),
            ProgrammingLanguage(id = "haml", name = "Haml", color = "#ece2a9"),
            ProgrammingLanguage(id = "handlebars", name = "Handlebars", color = "#f7931e"),
            ProgrammingLanguage(id = "harbour", name = "Harbour", color = "#0e60e3"),
            ProgrammingLanguage(id = "haskell", name = "Haskell", color = "#5e5086"),
            ProgrammingLanguage(id = "haxe", name = "Haxe", color = "#df7900"),
            ProgrammingLanguage(id = "hcl", name = "HCL"),
            ProgrammingLanguage(id = "hlsl", name = "HLSL"),
            ProgrammingLanguage(id = "html", name = "HTML", color = "#e34c26"),
            ProgrammingLanguage(id = "html%2Bdjango", name = "HTML+Django"),
            ProgrammingLanguage(id = "html%2Becr", name = "HTML+ECR"),
            ProgrammingLanguage(id = "html%2Beex", name = "HTML+EEX"),
            ProgrammingLanguage(id = "html%2Berb", name = "HTML+ERB"),
            ProgrammingLanguage(id = "html%2Bphp", name = "HTML+PHP"),
            ProgrammingLanguage(id = "http", name = "HTTP"),
            ProgrammingLanguage(id = "hy", name = "Hy", color = "#7790B2"),
            ProgrammingLanguage(id = "hyphy", name = "HyPhy"),
            ProgrammingLanguage(id = "idl", name = "IDL", color = "#a3522f"),
            ProgrammingLanguage(id = "idris", name = "Idris", color = "#b30000"),
            ProgrammingLanguage(id = "igor-pro", name = "IGOR Pro", color = "#0000cc"),
            ProgrammingLanguage(id = "inform-7", name = "Inform 7"),
            ProgrammingLanguage(id = "ini", name = "INI"),
            ProgrammingLanguage(id = "inno-setup", name = "Inno Setup"),
            ProgrammingLanguage(id = "io", name = "Io", color = "#a9188d"),
            ProgrammingLanguage(id = "ioke", name = "Ioke", color = "#078193"),
            ProgrammingLanguage(id = "irc-log", name = "IRC log"),
            ProgrammingLanguage(id = "isabelle", name = "Isabelle", color = "#FEFE00"),
            ProgrammingLanguage(id = "isabelle-root", name = "Isabelle ROOT"),
            ProgrammingLanguage(id = "j", name = "J", color = "#9EEDFF"),
            ProgrammingLanguage(id = "jasmin", name = "Jasmin"),
            ProgrammingLanguage(id = "java", name = "Java", color = "#b07219"),
            ProgrammingLanguage(id = "java-server-pages", name = "Java Server Pages"),
            ProgrammingLanguage(id = "javascript", name = "JavaScript", color = "#f1e05a"),
            ProgrammingLanguage(id = "jflex", name = "JFlex", color = "#DBCA00"),
            ProgrammingLanguage(id = "jison", name = "Jison"),
            ProgrammingLanguage(id = "jison-lex", name = "Jison Lex"),
            ProgrammingLanguage(id = "jolie", name = "Jolie", color = "#843179"),
            ProgrammingLanguage(id = "json", name = "JSON"),
            ProgrammingLanguage(id = "json5", name = "JSON5"),
            ProgrammingLanguage(id = "jsoniq", name = "JSONiq", color = "#40d47e"),
            ProgrammingLanguage(id = "jsonld", name = "JSONLD"),
            ProgrammingLanguage(id = "jsx", name = "JSX"),
            ProgrammingLanguage(id = "julia", name = "Julia", color = "#a270ba"),
            ProgrammingLanguage(id = "jupyter-notebook", name = "Jupyter Notebook", color = "#DA5B0B"),
            ProgrammingLanguage(id = "kicad-layout", name = "KiCad Layout"),
            ProgrammingLanguage(id = "kicad-legacy-layout", name = "KiCad Legacy Layout"),
            ProgrammingLanguage(id = "kicad-schematic", name = "KiCad Schematic"),
            ProgrammingLanguage(id = "kit", name = "Kit"),
            ProgrammingLanguage(id = "kotlin", name = "Kotlin", color = "#F18E33"),
            ProgrammingLanguage(id = "krl", name = "KRL", color = "#28430A"),
            ProgrammingLanguage(id = "labview", name = "LabVIEW"),
            ProgrammingLanguage(id = "lasso", name = "Lasso", color = "#999999"),
            ProgrammingLanguage(id = "latte", name = "Latte", color = "#f2a542"),
            ProgrammingLanguage(id = "lean", name = "Lean"),
            ProgrammingLanguage(id = "less", name = "Less", color = "#1d365d"),
            ProgrammingLanguage(id = "lex", name = "Lex", color = "#DBCA00"),
            ProgrammingLanguage(id = "lfe", name = "LFE", color = "#4C3023"),
            ProgrammingLanguage(id = "lilypond", name = "LilyPond"),
            ProgrammingLanguage(id = "limbo", name = "Limbo"),
            ProgrammingLanguage(id = "linker-script", name = "Linker Script"),
            ProgrammingLanguage(id = "linux-kernel-module", name = "Linux Kernel Module"),
            ProgrammingLanguage(id = "liquid", name = "Liquid", color = "#67b8de"),
            ProgrammingLanguage(id = "literate-agda", name = "Literate Agda"),
            ProgrammingLanguage(id = "literate-coffeescript", name = "Literate CoffeeScript"),
            ProgrammingLanguage(id = "literate-haskell", name = "Literate Haskell"),
            ProgrammingLanguage(id = "livescript", name = "LiveScript", color = "#499886"),
            ProgrammingLanguage(id = "llvm", name = "LLVM", color = "#185619"),
            ProgrammingLanguage(id = "logos", name = "Logos"),
            ProgrammingLanguage(id = "logtalk", name = "Logtalk"),
            ProgrammingLanguage(id = "lolcode", name = "LOLCODE", color = "#cc9900"),
            ProgrammingLanguage(id = "lookml", name = "LookML", color = "#652B81"),
            ProgrammingLanguage(id = "loomscript", name = "LoomScript"),
            ProgrammingLanguage(id = "lsl", name = "LSL", color = "#3d9970"),
            ProgrammingLanguage(id = "lua", name = "Lua", color = "#000080"),
            ProgrammingLanguage(id = "m", name = "M"),
            ProgrammingLanguage(id = "m4", name = "M4"),
            ProgrammingLanguage(id = "m4sugar", name = "M4Sugar"),
            ProgrammingLanguage(id = "makefile", name = "Makefile", color = "#427819"),
            ProgrammingLanguage(id = "mako", name = "Mako"),
            ProgrammingLanguage(id = "markdown", name = "Markdown", color = "#083fa1"),
            ProgrammingLanguage(id = "marko", name = "Marko", color = "#42bff2"),
            ProgrammingLanguage(id = "mask", name = "Mask", color = "#f97732"),
            ProgrammingLanguage(id = "mathematica", name = "Mathematica"),
            ProgrammingLanguage(id = "matlab", name = "Matlab"),
            ProgrammingLanguage(id = "maven-pom", name = "Maven POM"),
            ProgrammingLanguage(id = "max", name = "Max", color = "#c4a79c"),
            ProgrammingLanguage(id = "maxscript", name = "MAXScript", color = "#00a6a6"),
            ProgrammingLanguage(id = "mediawiki", name = "MediaWiki"),
            ProgrammingLanguage(id = "mercury", name = "Mercury", color = "#ff2b2b"),
            ProgrammingLanguage(id = "meson", name = "Meson", color = "#007800"),
            ProgrammingLanguage(id = "metal", name = "Metal", color = "#8f14e9"),
            ProgrammingLanguage(id = "minid", name = "MiniD"),
            ProgrammingLanguage(id = "mirah", name = "Mirah", color = "#c7a938"),
            ProgrammingLanguage(id = "modelica", name = "Modelica"),
            ProgrammingLanguage(id = "modula-2", name = "Modula-2"),
            ProgrammingLanguage(id = "module-management-system", name = "Module Management System"),
            ProgrammingLanguage(id = "monkey", name = "Monkey"),
            ProgrammingLanguage(id = "moocode", name = "Moocode"),
            ProgrammingLanguage(id = "moonscript", name = "MoonScript"),
            ProgrammingLanguage(id = "mql4", name = "MQL4", color = "#62A8D6"),
            ProgrammingLanguage(id = "mql5", name = "MQL5", color = "#4A76B8"),
            ProgrammingLanguage(id = "mtml", name = "MTML", color = "#b7e1f4"),
            ProgrammingLanguage(id = "muf", name = "MUF"),
            ProgrammingLanguage(id = "mupad", name = "mupad"),
            ProgrammingLanguage(id = "myghty", name = "Myghty"),
            ProgrammingLanguage(id = "ncl", name = "NCL", color = "#28431f"),
            ProgrammingLanguage(id = "nearley", name = "Nearley", color = "#990000"),
            ProgrammingLanguage(id = "nemerle", name = "Nemerle", color = "#3d3c6e"),
            ProgrammingLanguage(id = "nesc", name = "nesC", color = "#94B0C7"),
            ProgrammingLanguage(id = "netlinx", name = "NetLinx", color = "#0aa0ff"),
            ProgrammingLanguage(id = "netlinx%2Berb", name = "NetLinx+ERB", color = "#747faa"),
            ProgrammingLanguage(id = "netlogo", name = "NetLogo", color = "#ff6375"),
            ProgrammingLanguage(id = "newlisp", name = "NewLisp", color = "#87AED7"),
            ProgrammingLanguage(id = "nextflow", name = "Nextflow", color = "#3ac486"),
            ProgrammingLanguage(id = "nginx", name = "Nginx"),
            ProgrammingLanguage(id = "nim", name = "Nim", color = "#ffc200"),
            ProgrammingLanguage(id = "ninja", name = "Ninja"),
            ProgrammingLanguage(id = "nit", name = "Nit", color = "#009917"),
            ProgrammingLanguage(id = "nix", name = "Nix", color = "#7e7eff"),
            ProgrammingLanguage(id = "nl", name = "NL"),
            ProgrammingLanguage(id = "nsis", name = "NSIS"),
            ProgrammingLanguage(id = "nu", name = "Nu", color = "#c9df40"),
            ProgrammingLanguage(id = "numpy", name = "NumPy", color = "#9C8AF9"),
            ProgrammingLanguage(id = "objdump", name = "ObjDump"),
            ProgrammingLanguage(id = "objective-c", name = "Objective-C", color = "#438eff"),
            ProgrammingLanguage(id = "objective-c%2B%2B", name = "Objective-C++", color = "#6866fb"),
            ProgrammingLanguage(id = "objective-j", name = "Objective-J", color = "#ff0c5a"),
            ProgrammingLanguage(id = "ocaml", name = "OCaml", color = "#3be133"),
            ProgrammingLanguage(id = "omgrofl", name = "Omgrofl", color = "#cabbff"),
            ProgrammingLanguage(id = "ooc", name = "ooc", color = "#b0b77e"),
            ProgrammingLanguage(id = "opa", name = "Opa"),
            ProgrammingLanguage(id = "opal", name = "Opal", color = "#f7ede0"),
            ProgrammingLanguage(id = "opencl", name = "OpenCL"),
            ProgrammingLanguage(id = "openedge-abl", name = "OpenEdge ABL"),
            ProgrammingLanguage(id = "openrc-runscript", name = "OpenRC runscript"),
            ProgrammingLanguage(id = "openscad", name = "OpenSCAD"),
            ProgrammingLanguage(id = "opentype-feature-file", name = "OpenType Feature File"),
            ProgrammingLanguage(id = "org", name = "Org", color = "#77aa99"),
            ProgrammingLanguage(id = "ox", name = "Ox"),
            ProgrammingLanguage(id = "oxygene", name = "Oxygene", color = "#cdd0e3"),
            ProgrammingLanguage(id = "oz", name = "Oz", color = "#fab738"),
            ProgrammingLanguage(id = "p4", name = "P4", color = "#7055b5"),
            ProgrammingLanguage(id = "pan", name = "Pan", color = "#cc0000"),
            ProgrammingLanguage(id = "papyrus", name = "Papyrus", color = "#6600cc"),
            ProgrammingLanguage(id = "parrot", name = "Parrot", color = "#f3ca0a"),
            ProgrammingLanguage(id = "parrot-assembly", name = "Parrot Assembly"),
            ProgrammingLanguage(id = "parrot-internal-representation", name = "Parrot Internal Representation"),
            ProgrammingLanguage(id = "pascal", name = "Pascal", color = "#E3F171"),
            ProgrammingLanguage(id = "pawn", name = "PAWN"),
            ProgrammingLanguage(id = "pep8", name = "Pep8", color = "#C76F5B"),
            ProgrammingLanguage(id = "perl", name = "Perl", color = "#0298c3"),
            ProgrammingLanguage(id = "perl-6", name = "Perl 6"),
            ProgrammingLanguage(id = "php", name = "PHP", color = "#4F5D95"),
            ProgrammingLanguage(id = "pic", name = "Pic"),
            ProgrammingLanguage(id = "pickle", name = "Pickle"),
            ProgrammingLanguage(id = "picolisp", name = "PicoLisp"),
            ProgrammingLanguage(id = "piglatin", name = "PigLatin", color = "#fcd7de"),
            ProgrammingLanguage(id = "pike", name = "Pike", color = "#005390"),
            ProgrammingLanguage(id = "plpgsql", name = "PLpgSQL"),
            ProgrammingLanguage(id = "plsql", name = "PLSQL", color = "#dad8d8"),
            ProgrammingLanguage(id = "pod", name = "Pod"),
            ProgrammingLanguage(id = "pogoscript", name = "PogoScript", color = "#d80074"),
            ProgrammingLanguage(id = "pony", name = "Pony"),
            ProgrammingLanguage(id = "postcss", name = "PostCSS"),
            ProgrammingLanguage(id = "postscript", name = "PostScript", color = "#da291c"),
            ProgrammingLanguage(id = "pov-ray-sdl", name = "POV-Ray SDL"),
            ProgrammingLanguage(id = "powerbuilder", name = "PowerBuilder", color = "#8f0f8d"),
            ProgrammingLanguage(id = "powershell", name = "PowerShell", color = "#012456"),
            ProgrammingLanguage(id = "processing", name = "Processing", color = "#0096D8"),
            ProgrammingLanguage(id = "prolog", name = "Prolog", color = "#74283c"),
            ProgrammingLanguage(id = "propeller-spin", name = "Propeller Spin", color = "#7fa2a7"),
            ProgrammingLanguage(id = "protocol-buffer", name = "Protocol Buffer"),
            ProgrammingLanguage(id = "public-key", name = "Public Key"),
            ProgrammingLanguage(id = "pug", name = "Pug", color = "#a86454"),
            ProgrammingLanguage(id = "puppet", name = "Puppet", color = "#302B6D"),
            ProgrammingLanguage(id = "pure-data", name = "Pure Data"),
            ProgrammingLanguage(id = "purebasic", name = "PureBasic", color = "#5a6986"),
            ProgrammingLanguage(id = "purescript", name = "PureScript", color = "#1D222D"),
            ProgrammingLanguage(id = "python", name = "Python", color = "#3572A5"),
            ProgrammingLanguage(id = "python-console", name = "Python console"),
            ProgrammingLanguage(id = "python-traceback", name = "Python traceback"),
            ProgrammingLanguage(id = "qmake", name = "QMake"),
            ProgrammingLanguage(id = "qml", name = "QML", color = "#44a51c"),
            ProgrammingLanguage(id = "r", name = "R", color = "#198CE7"),
            ProgrammingLanguage(id = "racket", name = "Racket", color = "#3c5caa"),
            ProgrammingLanguage(id = "ragel", name = "Ragel", color = "#9d5200"),
            ProgrammingLanguage(id = "raml", name = "RAML", color = "#77d9fb"),
            ProgrammingLanguage(id = "rascal", name = "Rascal", color = "#fffaa0"),
            ProgrammingLanguage(id = "raw-token-data", name = "Raw token data"),
            ProgrammingLanguage(id = "rdoc", name = "RDoc"),
            ProgrammingLanguage(id = "realbasic", name = "REALbasic"),
            ProgrammingLanguage(id = "reason", name = "Reason", color = "#ff5847"),
            ProgrammingLanguage(id = "rebol", name = "Rebol", color = "#358a5b"),
            ProgrammingLanguage(id = "red", name = "Red", color = "#f50000"),
            ProgrammingLanguage(id = "redcode", name = "Redcode"),
            ProgrammingLanguage(id = "regular-expression", name = "Regular Expression"),
            ProgrammingLanguage(id = "ren'py", name = "Ren'Py", color = "#ff7f7f"),
            ProgrammingLanguage(id = "renderscript", name = "RenderScript"),
            ProgrammingLanguage(id = "restructuredtext", name = "reStructuredText"),
            ProgrammingLanguage(id = "rexx", name = "REXX"),
            ProgrammingLanguage(id = "rhtml", name = "RHTML"),
            ProgrammingLanguage(id = "ring", name = "Ring", color = "#2D54CB"),
            ProgrammingLanguage(id = "rmarkdown", name = "RMarkdown"),
            ProgrammingLanguage(id = "robotframework", name = "RobotFramework"),
            ProgrammingLanguage(id = "roff", name = "Roff", color = "#ecdebe"),
            ProgrammingLanguage(id = "rouge", name = "Rouge", color = "#cc0088"),
            ProgrammingLanguage(id = "rpc", name = "RPC"),
            ProgrammingLanguage(id = "rpm-spec", name = "RPM Spec"),
            ProgrammingLanguage(id = "ruby", name = "Ruby", color = "#701516"),
            ProgrammingLanguage(id = "runoff", name = "RUNOFF", color = "#665a4e"),
            ProgrammingLanguage(id = "rust", name = "Rust", color = "#dea584"),
            ProgrammingLanguage(id = "sage", name = "Sage"),
            ProgrammingLanguage(id = "saltstack", name = "SaltStack", color = "#646464"),
            ProgrammingLanguage(id = "sas", name = "SAS", color = "#B34936"),
            ProgrammingLanguage(id = "sass", name = "Sass", color = "#a53b70"),
            ProgrammingLanguage(id = "scala", name = "Scala", color = "#c22d40"),
            ProgrammingLanguage(id = "scaml", name = "Scaml", color = "#bd181a"),
            ProgrammingLanguage(id = "scheme", name = "Scheme", color = "#1e4aec"),
            ProgrammingLanguage(id = "scilab", name = "Scilab"),
            ProgrammingLanguage(id = "scss", name = "SCSS", color = "#c6538c"),
            ProgrammingLanguage(id = "sed", name = "sed", color = "#64b970"),
            ProgrammingLanguage(id = "self", name = "Self", color = "#0579aa"),
            ProgrammingLanguage(id = "shaderlab", name = "ShaderLab"),
            ProgrammingLanguage(id = "shell", name = "Shell", color = "#89e051"),
            ProgrammingLanguage(id = "shellsession", name = "ShellSession"),
            ProgrammingLanguage(id = "shen", name = "Shen", color = "#120F14"),
            ProgrammingLanguage(id = "slash", name = "Slash", color = "#007eff"),
            ProgrammingLanguage(id = "slim", name = "Slim", color = "#2b2b2b"),
            ProgrammingLanguage(id = "smali", name = "Smali"),
            ProgrammingLanguage(id = "smalltalk", name = "Smalltalk", color = "#596706"),
            ProgrammingLanguage(id = "smarty", name = "Smarty"),
            ProgrammingLanguage(id = "smt", name = "SMT"),
            ProgrammingLanguage(id = "solidity", name = "Solidity", color = "#AA6746"),
            ProgrammingLanguage(id = "sourcepawn", name = "SourcePawn", color = "#f69e1d"),
            ProgrammingLanguage(id = "sparql", name = "SPARQL"),
            ProgrammingLanguage(id = "spline-font-database", name = "Spline Font Database"),
            ProgrammingLanguage(id = "sqf", name = "SQF", color = "#3F3F3F"),
            ProgrammingLanguage(id = "sql", name = "SQL"),
            ProgrammingLanguage(id = "sqlpl", name = "SQLPL"),
            ProgrammingLanguage(id = "squirrel", name = "Squirrel", color = "#800000"),
            ProgrammingLanguage(id = "srecode-template", name = "SRecode Template", color = "#348a34"),
            ProgrammingLanguage(id = "stan", name = "Stan", color = "#b2011d"),
            ProgrammingLanguage(id = "standard-ml", name = "Standard ML", color = "#dc566d"),
            ProgrammingLanguage(id = "stata", name = "Stata"),
            ProgrammingLanguage(id = "ston", name = "STON"),
            ProgrammingLanguage(id = "stylus", name = "Stylus", color = "#ff6347"),
            ProgrammingLanguage(id = "sublime-text-config", name = "Sublime Text Config"),
            ProgrammingLanguage(id = "subrip-text", name = "SubRip Text"),
            ProgrammingLanguage(id = "sugarss", name = "SugarSS"),
            ProgrammingLanguage(id = "supercollider", name = "SuperCollider", color = "#46390b"),
            ProgrammingLanguage(id = "svg", name = "SVG", color = "#ff9900"),
            ProgrammingLanguage(id = "swift", name = "Swift", color = "#ffac45"),
            ProgrammingLanguage(id = "systemverilog", name = "SystemVerilog", color = "#DAE1C2"),
            ProgrammingLanguage(id = "tcl", name = "Tcl", color = "#e4cc98"),
            ProgrammingLanguage(id = "tcsh", name = "Tcsh"),
            ProgrammingLanguage(id = "tea", name = "Tea"),
            ProgrammingLanguage(id = "terra", name = "Terra", color = "#00004c"),
            ProgrammingLanguage(id = "tex", name = "TeX", color = "#3D6117"),
            ProgrammingLanguage(id = "text", name = "Text"),
            ProgrammingLanguage(id = "textile", name = "Textile"),
            ProgrammingLanguage(id = "thrift", name = "Thrift"),
            ProgrammingLanguage(id = "ti-program", name = "TI Program", color = "#A0AA87"),
            ProgrammingLanguage(id = "tla", name = "TLA"),
            ProgrammingLanguage(id = "toml", name = "TOML"),
            ProgrammingLanguage(id = "turing", name = "Turing", color = "#cf142b"),
            ProgrammingLanguage(id = "turtle", name = "Turtle"),
            ProgrammingLanguage(id = "twig", name = "Twig", color = "#c1d026"),
            ProgrammingLanguage(id = "txl", name = "TXL"),
            ProgrammingLanguage(id = "type-language", name = "Type Language"),
            ProgrammingLanguage(id = "typescript", name = "TypeScript", color = "#2b7489"),
            ProgrammingLanguage(id = "unified-parallel-c", name = "Unified Parallel C", color = "#4e3617"),
            ProgrammingLanguage(id = "unity3d-asset", name = "Unity3D Asset"),
            ProgrammingLanguage(id = "unix-assembly", name = "Unix Assembly"),
            ProgrammingLanguage(id = "uno", name = "Uno", color = "#9933cc"),
            ProgrammingLanguage(id = "unrealscript", name = "UnrealScript", color = "#a54c4d"),
            ProgrammingLanguage(id = "urweb", name = "UrWeb"),
            ProgrammingLanguage(id = "vala", name = "Vala", color = "#fbe5cd"),
            ProgrammingLanguage(id = "vcl", name = "VCL", color = "#148AA8"),
            ProgrammingLanguage(id = "verilog", name = "Verilog", color = "#b2b7f8"),
            ProgrammingLanguage(id = "vhdl", name = "VHDL", color = "#adb2cb"),
            ProgrammingLanguage(id = "vim-script", name = "Vim script", color = "#199f4b"),
            ProgrammingLanguage(id = "visual-basic", name = "Visual Basic"),
            ProgrammingLanguage(id = "volt", name = "Volt", color = "#1F1F1F"),
            ProgrammingLanguage(id = "vue", name = "Vue", color = "#2c3e50"),
            ProgrammingLanguage(id = "wavefront-material", name = "Wavefront Material"),
            ProgrammingLanguage(id = "wavefront-object", name = "Wavefront Object"),
            ProgrammingLanguage(id = "wdl", name = "wdl", color = "#42f1f4"),
            ProgrammingLanguage(id = "web-ontology-language", name = "Web Ontology Language"),
            ProgrammingLanguage(id = "webassembly", name = "WebAssembly", color = "#04133b"),
            ProgrammingLanguage(id = "webidl", name = "WebIDL"),
            ProgrammingLanguage(id = "wisp", name = "wisp", color = "#7582D1"),
            ProgrammingLanguage(id = "world-of-warcraft-addon-data", name = "World of Warcraft Addon Data"),
            ProgrammingLanguage(id = "x10", name = "X10", color = "#4B6BEF"),
            ProgrammingLanguage(id = "xbase", name = "xBase", color = "#403a40"),
            ProgrammingLanguage(id = "xc", name = "XC", color = "#99DA07"),
            ProgrammingLanguage(id = "xcompose", name = "XCompose"),
            ProgrammingLanguage(id = "xml", name = "XML"),
            ProgrammingLanguage(id = "xojo", name = "Xojo"),
            ProgrammingLanguage(id = "xpages", name = "XPages"),
            ProgrammingLanguage(id = "xpm", name = "XPM"),
            ProgrammingLanguage(id = "xproc", name = "XProc"),
            ProgrammingLanguage(id = "xquery", name = "XQuery", color = "#5232e7"),
            ProgrammingLanguage(id = "xs", name = "XS"),
            ProgrammingLanguage(id = "xslt", name = "XSLT", color = "#EB8CEB"),
            ProgrammingLanguage(id = "xtend", name = "Xtend"),
            ProgrammingLanguage(id = "yacc", name = "Yacc", color = "#4B6C4B"),
            ProgrammingLanguage(id = "yaml", name = "YAML", color = "#cb171e"),
            ProgrammingLanguage(id = "yang", name = "YANG"),
            ProgrammingLanguage(id = "yara", name = "YARA", color = "#220000"),
            ProgrammingLanguage(id = "zephir", name = "Zephir", color = "#118f9e"),
            ProgrammingLanguage(id = "zimpl", name = "Zimpl"),
        )
    }
}
